[package]
name = "winc"
version = "0.1.0"
edition = "2021"
authors = ["TeamDman"]
license = "Mozilla Public License Version 2.0"
repository = "https://github.com/TeamDman/winc"
homepaghe = "https://github.com/TeamDman/winc"
readme = "README.md"
keywords = ["winc","windows","screen-capture"]

[dependencies]
